/**
 * zh-CN display translations for the first Agentflow V2 metadata shard.
 *
 * Stable machine identifiers remain in the tuple keys. IANA timezone values,
 * protocol names, MIME types, model terms, and executable placeholders are kept
 * verbatim where translating them would change their technical meaning.
 */
export const ZH_CN_AGENTFLOW_A: ReadonlyArray<readonly [string, string]> = [
    ['node.agentAgentflow.root.description@57c205ef922c', '在运行时动态选择并使用工具，实现多步推理'],
    ['node.agentAgentflow.root.label@11b39c93777e', '智能体'],
    ['node.agentAgentflow.root/inputs/agentEnableMemory.description@3b57e4b0594c', '为当前对话线程启用记忆'],
    ['node.agentAgentflow.root/inputs/agentEnableMemory.label@c9cd83363056', '启用记忆'],
    [
        'node.agentAgentflow.root/inputs/agentKnowledgeDocumentStores.description@1b66a532d096',
        '为智能体提供不同文档来源的上下文。文档库必须预先完成 Upsert。'
    ],
    ['node.agentAgentflow.root/inputs/agentKnowledgeDocumentStores.label@b97a7390b610', '知识（文档库）'],
    ['node.agentAgentflow.root/inputs/agentKnowledgeDocumentStores/array/docStoreDescription.label@1bc30f109f14', '描述知识'],
    [
        'node.agentAgentflow.root/inputs/agentKnowledgeDocumentStores/array/docStoreDescription.placeholder@772e2ce12a54',
        '描述知识库的内容，帮助 AI 判断何时以及如何检索正确信息'
    ],
    ['node.agentAgentflow.root/inputs/agentKnowledgeDocumentStores/array/documentStore.label@31019271716f', '文档库'],
    ['node.agentAgentflow.root/inputs/agentKnowledgeDocumentStores/array/returnSourceDocuments.label@deb5de0aa0b6', '返回源文档'],
    [
        'node.agentAgentflow.root/inputs/agentKnowledgeVSEmbeddings.description@518ed9a7f287',
        '通过现有向量库和嵌入模型，为智能体提供不同文档来源的上下文'
    ],
    ['node.agentAgentflow.root/inputs/agentKnowledgeVSEmbeddings.label@e6eb3ac220b5', '知识（向量嵌入）'],
    ['node.agentAgentflow.root/inputs/agentKnowledgeVSEmbeddings/array/embeddingModel.label@860ec100606b', '嵌入模型'],
    ['node.agentAgentflow.root/inputs/agentKnowledgeVSEmbeddings/array/knowledgeDescription.label@1bc30f109f14', '描述知识'],
    [
        'node.agentAgentflow.root/inputs/agentKnowledgeVSEmbeddings/array/knowledgeDescription.placeholder@772e2ce12a54',
        '描述知识库的内容，帮助 AI 判断何时以及如何检索正确信息'
    ],
    ['node.agentAgentflow.root/inputs/agentKnowledgeVSEmbeddings/array/knowledgeName.label@4bf60fe77f34', '知识名称'],
    [
        'node.agentAgentflow.root/inputs/agentKnowledgeVSEmbeddings/array/knowledgeName.placeholder@4297adcfca8d',
        '为知识库设置一个简短名称，帮助 AI 判断何时以及如何检索正确信息'
    ],
    ['node.agentAgentflow.root/inputs/agentKnowledgeVSEmbeddings/array/returnSourceDocuments.label@deb5de0aa0b6', '返回源文档'],
    ['node.agentAgentflow.root/inputs/agentKnowledgeVSEmbeddings/array/vectorStore.label@ae81a470f59d', '向量库'],
    ['node.agentAgentflow.root/inputs/agentMemoryMaxTokenLimit.description@5abdf990bfa7', '达到 Token 上限后对对话进行摘要，默认值为 2000'],
    ['node.agentAgentflow.root/inputs/agentMemoryMaxTokenLimit.label@1dcc214bcf11', '最大 Token 数'],
    ['node.agentAgentflow.root/inputs/agentMemoryType.label@e1236313c834', '记忆类型'],
    ['node.agentAgentflow.root/inputs/agentMemoryType/options/allMessages.description@050924374da0', '获取对话中的全部消息'],
    ['node.agentAgentflow.root/inputs/agentMemoryType/options/allMessages.label@020dc04d5347', '全部消息'],
    ['node.agentAgentflow.root/inputs/agentMemoryType/options/conversationSummary.description@d2752e1fd9c6', '对完整对话进行摘要'],
    ['node.agentAgentflow.root/inputs/agentMemoryType/options/conversationSummary.label@01d3797563b1', '对话摘要'],
    [
        'node.agentAgentflow.root/inputs/agentMemoryType/options/conversationSummaryBuffer.description@5abdf990bfa7',
        '达到 Token 上限后对对话进行摘要，默认值为 2000'
    ],
    ['node.agentAgentflow.root/inputs/agentMemoryType/options/conversationSummaryBuffer.label@9cccef88e094', '对话摘要缓冲区'],
    ['node.agentAgentflow.root/inputs/agentMemoryType/options/windowSize.description@2375b0f0cb00', '使用固定窗口显示最近 N 条消息'],
    ['node.agentAgentflow.root/inputs/agentMemoryType/options/windowSize.label@9010362dc031', '窗口大小'],
    ['node.agentAgentflow.root/inputs/agentMemoryWindowSize.description@2375b0f0cb00', '使用固定窗口显示最近 N 条消息'],
    ['node.agentAgentflow.root/inputs/agentMemoryWindowSize.label@9010362dc031', '窗口大小'],
    ['node.agentAgentflow.root/inputs/agentMessages.label@04d7b4833927', '消息'],
    ['node.agentAgentflow.root/inputs/agentMessages/array/content.label@47bd29075f8b', '内容'],
    ['node.agentAgentflow.root/inputs/agentMessages/array/role.label@14736a2eb9f4', '角色'],
    ['node.agentAgentflow.root/inputs/agentMessages/array/role/options/assistant.label@391e40515277', '助手'],
    ['node.agentAgentflow.root/inputs/agentMessages/array/role/options/developer.label@3fb7b39416f1', '开发者'],
    ['node.agentAgentflow.root/inputs/agentMessages/array/role/options/system.label@6725e7bbcd28', '系统'],
    ['node.agentAgentflow.root/inputs/agentMessages/array/role/options/user.label@b512d97e7cbf', '用户'],
    ['node.agentAgentflow.root/inputs/agentModel.label@5e2c614c23f0', '模型'],
    ['node.agentAgentflow.root/inputs/agentReturnResponseAs.label@ba98ff33219c', '响应返回为'],
    ['node.agentAgentflow.root/inputs/agentReturnResponseAs/options/assistantMessage.label@a23e1001767c', '助手消息'],
    ['node.agentAgentflow.root/inputs/agentReturnResponseAs/options/userMessage.label@fb33af32d694', '用户消息'],
    ['node.agentAgentflow.root/inputs/agentStructuredOutput.description@a20b3f874c20', '指示智能体按照 JSON 结构定义输出'],
    ['node.agentAgentflow.root/inputs/agentStructuredOutput.label@5212deb43b7f', 'JSON 结构化输出'],
    ['node.agentAgentflow.root/inputs/agentStructuredOutput/array/description.label@526e0087cc3f', '说明'],
    ['node.agentAgentflow.root/inputs/agentStructuredOutput/array/description.placeholder@c65146c4dfde', '键的说明'],
    ['node.agentAgentflow.root/inputs/agentStructuredOutput/array/enumValues.description@389254c5e32d', '枚举值，使用逗号分隔'],
    ['node.agentAgentflow.root/inputs/agentStructuredOutput/array/enumValues.label@36a902b279bd', '枚举值'],
    ['node.agentAgentflow.root/inputs/agentStructuredOutput/array/enumValues.placeholder@ed8416b4f900', '值1, 值2, 值3'],
    ['node.agentAgentflow.root/inputs/agentStructuredOutput/array/jsonSchema.description@484e1d18142a', '结构化输出所使用的 JSON 架构'],
    ['node.agentAgentflow.root/inputs/agentStructuredOutput/array/jsonSchema.label@13a8f29ba149', 'JSON 架构'],
    [
        'node.agentAgentflow.root/inputs/agentStructuredOutput/array/jsonSchema.placeholder@777f2a412ac4',
        '{\n    "answer": {\n        "type": "string",\n        "description": "答案值"\n    },\n    "reason": {\n        "type": "string",\n        "description": "答案依据"\n    },\n    "optional": {\n        "type": "boolean"\n    },\n    "count": {\n        "type": "number"\n    },\n    "children": {\n        "type": "array",\n        "items": {\n            "type": "object",\n            "properties": {\n                "value": {\n                    "type": "string",\n                    "description": "子项的答案值"\n                }\n            }\n        }\n    }\n}'
    ],
    ['node.agentAgentflow.root/inputs/agentStructuredOutput/array/key.label@99a52df3ff3d', '键'],
    ['node.agentAgentflow.root/inputs/agentStructuredOutput/array/type.label@baaddf70fb5d', '类型'],
    ['node.agentAgentflow.root/inputs/agentStructuredOutput/array/type/options/boolean.label@a066ff921096', '布尔值'],
    ['node.agentAgentflow.root/inputs/agentStructuredOutput/array/type/options/enum.label@54108dafaac5', '枚举'],
    ['node.agentAgentflow.root/inputs/agentStructuredOutput/array/type/options/jsonArray.label@bfbf8f8f40f8', 'JSON 数组'],
    ['node.agentAgentflow.root/inputs/agentStructuredOutput/array/type/options/number.label@bd82cf16699b', '数字'],
    ['node.agentAgentflow.root/inputs/agentStructuredOutput/array/type/options/string.label@b2ef230e7f4f', '字符串'],
    ['node.agentAgentflow.root/inputs/agentStructuredOutput/array/type/options/stringArray.label@73eddd534239', '字符串数组'],
    ['node.agentAgentflow.root/inputs/agentTools.label@ea93d6a262ec', '工具'],
    ['node.agentAgentflow.root/inputs/agentTools/array/agentSelectedTool.label@2e53bdcd0740', '工具'],
    ['node.agentAgentflow.root/inputs/agentTools/array/agentSelectedToolRequiresHumanInput.label@19c084ec691e', '需要人工输入'],
    ['node.agentAgentflow.root/inputs/agentToolsBuiltInAnthropic.label@083a8ec10b16', 'Anthropic 内置工具'],
    [
        'node.agentAgentflow.root/inputs/agentToolsBuiltInAnthropic/options/web_fetch_20250910.description@0dcff9ba0e53',
        '获取指定网页的完整内容'
    ],
    ['node.agentAgentflow.root/inputs/agentToolsBuiltInAnthropic/options/web_fetch_20250910.label@5c1acea9c9b0', '网页获取'],
    [
        'node.agentAgentflow.root/inputs/agentToolsBuiltInAnthropic/options/web_search_20250305.description@6de7a8148689',
        '在网页中搜索最新信息'
    ],
    ['node.agentAgentflow.root/inputs/agentToolsBuiltInAnthropic/options/web_search_20250305.label@d04fc7d7e197', '网页搜索'],
    ['node.agentAgentflow.root/inputs/agentToolsBuiltInGemini.label@1af573a07da8', 'Gemini 内置工具'],
    [
        'node.agentAgentflow.root/inputs/agentToolsBuiltInGemini/options/codeExecution.description@080eeefc2b72',
        '在沙箱环境中编写并运行 Python 代码'
    ],
    ['node.agentAgentflow.root/inputs/agentToolsBuiltInGemini/options/codeExecution.label@afc798a41a0c', '代码执行'],
    ['node.agentAgentflow.root/inputs/agentToolsBuiltInGemini/options/googleSearch.description@b7cc4663779b', '搜索实时网页内容'],
    ['node.agentAgentflow.root/inputs/agentToolsBuiltInGemini/options/googleSearch.label@3be7914e361c', 'Google 搜索'],
    ['node.agentAgentflow.root/inputs/agentToolsBuiltInGemini/options/urlContext.description@0d4d133b1eeb', '从指定 URL 提取内容'],
    ['node.agentAgentflow.root/inputs/agentToolsBuiltInGemini/options/urlContext.label@5eff793b47ed', 'URL 上下文'],
    ['node.agentAgentflow.root/inputs/agentToolsBuiltInOpenAI.label@42d8c33f4b51', 'OpenAI 内置工具'],
    [
        'node.agentAgentflow.root/inputs/agentToolsBuiltInOpenAI/options/code_interpreter.description@080eeefc2b72',
        '在沙箱环境中编写并运行 Python 代码'
    ],
    ['node.agentAgentflow.root/inputs/agentToolsBuiltInOpenAI/options/code_interpreter.label@730d81336717', '代码解释器'],
    ['node.agentAgentflow.root/inputs/agentToolsBuiltInOpenAI/options/image_generation.description@894cb71a1a30', '根据文本提示词生成图像'],
    ['node.agentAgentflow.root/inputs/agentToolsBuiltInOpenAI/options/image_generation.label@8f4716e674b9', '图像生成'],
    ['node.agentAgentflow.root/inputs/agentToolsBuiltInOpenAI/options/web_search_preview.description@6de7a8148689', '在网页中搜索最新信息'],
    ['node.agentAgentflow.root/inputs/agentToolsBuiltInOpenAI/options/web_search_preview.label@d04fc7d7e197', '网页搜索'],
    ['node.agentAgentflow.root/inputs/agentUpdateState.description@e1092381d050', '在工作流执行期间更新运行时状态'],
    ['node.agentAgentflow.root/inputs/agentUpdateState.label@12cccc3a460b', '更新流程状态'],
    ['node.agentAgentflow.root/inputs/agentUpdateState/array/key.label@99a52df3ff3d', '键'],
    ['node.agentAgentflow.root/inputs/agentUpdateState/array/value.label@8e37953d23da', '值'],
    ['node.agentAgentflow.root/inputs/agentUserMessage.description@92396550e25c', '在对话末尾以用户消息形式添加一条输入消息'],
    ['node.agentAgentflow.root/inputs/agentUserMessage.label@333ca21cd322', '输入消息'],
    ['node.conditionAgentAgentflow.root.description@dbd6d177f727', '使用智能体根据动态条件对流程进行分支'],
    ['node.conditionAgentAgentflow.root.label@934a18a20311', '条件智能体'],
    ['node.conditionAgentAgentflow.root/outputs/0.description@1d1299194335', '条件 0'],
    ['node.conditionAgentAgentflow.root/outputs/0.label@5feceb66ffc8', '0'],
    ['node.conditionAgentAgentflow.root/outputs/1.description@9c77d72eccf3', '否则'],
    ['node.conditionAgentAgentflow.root/outputs/1.label@6b86b273ff34', '1'],
    ['node.conditionAgentAgentflow.root/inputs/conditionAgentEnableMemory.description@3b57e4b0594c', '为当前对话线程启用记忆'],
    ['node.conditionAgentAgentflow.root/inputs/conditionAgentEnableMemory.label@c9cd83363056', '启用记忆'],
    ['node.conditionAgentAgentflow.root/inputs/conditionAgentInput.description@c07fa36f69df', '供条件智能体使用的输入'],
    ['node.conditionAgentAgentflow.root/inputs/conditionAgentInput.label@36ecb4f86691', '输入'],
    ['node.conditionAgentAgentflow.root/inputs/conditionAgentInstructions.description@8b150e5bcb62', '条件智能体应执行任务的通用说明'],
    ['node.conditionAgentAgentflow.root/inputs/conditionAgentInstructions.label@934652dce41d', '指令'],
    ['node.conditionAgentAgentflow.root/inputs/conditionAgentInstructions.placeholder@404f0307f912', '判断用户是否有兴趣了解 AI'],
    [
        'node.conditionAgentAgentflow.root/inputs/conditionAgentMemoryMaxTokenLimit.description@5abdf990bfa7',
        '达到 Token 上限后对对话进行摘要，默认值为 2000'
    ],
    ['node.conditionAgentAgentflow.root/inputs/conditionAgentMemoryMaxTokenLimit.label@1dcc214bcf11', '最大 Token 数'],
    ['node.conditionAgentAgentflow.root/inputs/conditionAgentMemoryType.label@e1236313c834', '记忆类型'],
    [
        'node.conditionAgentAgentflow.root/inputs/conditionAgentMemoryType/options/allMessages.description@050924374da0',
        '获取对话中的全部消息'
    ],
    ['node.conditionAgentAgentflow.root/inputs/conditionAgentMemoryType/options/allMessages.label@020dc04d5347', '全部消息'],
    [
        'node.conditionAgentAgentflow.root/inputs/conditionAgentMemoryType/options/conversationSummary.description@d2752e1fd9c6',
        '对完整对话进行摘要'
    ],
    ['node.conditionAgentAgentflow.root/inputs/conditionAgentMemoryType/options/conversationSummary.label@01d3797563b1', '对话摘要'],
    [
        'node.conditionAgentAgentflow.root/inputs/conditionAgentMemoryType/options/conversationSummaryBuffer.description@5abdf990bfa7',
        '达到 Token 上限后对对话进行摘要，默认值为 2000'
    ],
    [
        'node.conditionAgentAgentflow.root/inputs/conditionAgentMemoryType/options/conversationSummaryBuffer.label@9cccef88e094',
        '对话摘要缓冲区'
    ],
    [
        'node.conditionAgentAgentflow.root/inputs/conditionAgentMemoryType/options/windowSize.description@2375b0f0cb00',
        '使用固定窗口显示最近 N 条消息'
    ],
    ['node.conditionAgentAgentflow.root/inputs/conditionAgentMemoryType/options/windowSize.label@9010362dc031', '窗口大小'],
    ['node.conditionAgentAgentflow.root/inputs/conditionAgentMemoryWindowSize.description@2375b0f0cb00', '使用固定窗口显示最近 N 条消息'],
    ['node.conditionAgentAgentflow.root/inputs/conditionAgentMemoryWindowSize.label@9010362dc031', '窗口大小'],
    ['node.conditionAgentAgentflow.root/inputs/conditionAgentModel.label@5e2c614c23f0', '模型'],
    [
        'node.conditionAgentAgentflow.root/inputs/conditionAgentOverrideSystemPrompt.description@f5b6ff00c908',
        '覆盖条件智能体的初始系统提示词'
    ],
    ['node.conditionAgentAgentflow.root/inputs/conditionAgentOverrideSystemPrompt.label@889290bc82cf', '覆盖系统提示词'],
    ['node.conditionAgentAgentflow.root/inputs/conditionAgentScenarios.description@57b7307b6e32', '定义用于分流的条件场景'],
    ['node.conditionAgentAgentflow.root/inputs/conditionAgentScenarios.label@72fa5509b2f9', '场景'],
    ['node.conditionAgentAgentflow.root/inputs/conditionAgentScenarios/array/scenario.label@2fcb5d374697', '场景'],
    ['node.conditionAgentAgentflow.root/inputs/conditionAgentScenarios/array/scenario.placeholder@f0f7f462f07d', '用户正在询问披萨'],
    [
        'node.conditionAgentAgentflow.root/inputs/conditionAgentSystemPrompt.description@50d6ed65d724',
        '仅供专家使用。修改此项可能显著改变智能体行为；如不确定，请保留默认值。'
    ],
    ['node.conditionAgentAgentflow.root/inputs/conditionAgentSystemPrompt.label@f8cdceaae7d5', '条件智能体系统提示词'],
    ['node.conditionAgentflow.root.description@bafe5de061ea', '根据 If/Else 条件对流程进行分支'],
    ['node.conditionAgentflow.root.label@39b36d38d6eb', '条件'],
    ['node.conditionAgentflow.root/outputs/0.description@1d1299194335', '条件 0'],
    ['node.conditionAgentflow.root/outputs/0.label@5feceb66ffc8', '0'],
    ['node.conditionAgentflow.root/outputs/1.description@9c77d72eccf3', '否则'],
    ['node.conditionAgentflow.root/outputs/1.label@6b86b273ff34', '1'],
    ['node.conditionAgentflow.root/inputs/conditions.description@2b9531a1fa05', '要比较的值'],
    ['node.conditionAgentflow.root/inputs/conditions.label@97d4be896069', '条件'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation.description@b60da65cb8c8', '操作类型'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation.description@b60da65cb8c8', '操作类型'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation.description@b60da65cb8c8', '操作类型'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation.label@0f044feb6ca7', '操作'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation.label@0f044feb6ca7', '操作'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation.label@0f044feb6ca7', '操作'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation/options/contains.label@2eaecb3d0cf1', '包含'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation/options/endsWith.label@1a77d555bedb', '结尾是'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation/options/equal.label@374c25297421', '等于'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation/options/equal.label@374c25297421', '等于'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation/options/equal.label@374c25297421', '等于'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation/options/isEmpty.label@906dd5bad339', '为空'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation/options/isEmpty.label@906dd5bad339', '为空'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation/options/larger.label@b05e2520a37f', '大于'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation/options/largerEqual.label@c512cc7dbca3', '大于或等于'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation/options/notContains.label@bfccbdda37b8', '不包含'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation/options/notEmpty.label@899fbec47c41', '不为空'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation/options/notEmpty.label@899fbec47c41', '不为空'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation/options/notEqual.label@e842e15e0e7e', '不等于'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation/options/notEqual.label@e842e15e0e7e', '不等于'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation/options/notEqual.label@e842e15e0e7e', '不等于'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation/options/regex.label@0f2712521d50', '正则表达式'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation/options/smaller.label@00417195b1e2', '小于'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation/options/smallerEqual.label@34b7bada2e59', '小于或等于'],
    ['node.conditionAgentflow.root/inputs/conditions/array/operation/options/startsWith.label@72927b6fdb53', '开头是'],
    ['node.conditionAgentflow.root/inputs/conditions/array/type.label@baaddf70fb5d', '类型'],
    ['node.conditionAgentflow.root/inputs/conditions/array/type/options/boolean.label@a066ff921096', '布尔值'],
    ['node.conditionAgentflow.root/inputs/conditions/array/type/options/number.label@bd82cf16699b', '数字'],
    ['node.conditionAgentflow.root/inputs/conditions/array/type/options/string.label@b2ef230e7f4f', '字符串'],
    ['node.conditionAgentflow.root/inputs/conditions/array/value1.description@23d0d35197d1', '参与比较的第一个值'],
    ['node.conditionAgentflow.root/inputs/conditions/array/value1.description@23d0d35197d1', '参与比较的第一个值'],
    ['node.conditionAgentflow.root/inputs/conditions/array/value1.description@23d0d35197d1', '参与比较的第一个值'],
    ['node.conditionAgentflow.root/inputs/conditions/array/value1.label@06edae26c5ac', '值 1'],
    ['node.conditionAgentflow.root/inputs/conditions/array/value1.label@06edae26c5ac', '值 1'],
    ['node.conditionAgentflow.root/inputs/conditions/array/value1.label@06edae26c5ac', '值 1'],
    ['node.conditionAgentflow.root/inputs/conditions/array/value2.description@52f807b76e0e', '参与比较的第二个值'],
    ['node.conditionAgentflow.root/inputs/conditions/array/value2.description@52f807b76e0e', '参与比较的第二个值'],
    ['node.conditionAgentflow.root/inputs/conditions/array/value2.description@52f807b76e0e', '参与比较的第二个值'],
    ['node.conditionAgentflow.root/inputs/conditions/array/value2.label@a1fd6064951e', '值 2'],
    ['node.conditionAgentflow.root/inputs/conditions/array/value2.label@a1fd6064951e', '值 2'],
    ['node.conditionAgentflow.root/inputs/conditions/array/value2.label@a1fd6064951e', '值 2'],
    ['node.llmAgentflow.root.description@0d5be787553d', '使用大语言模型分析用户输入并生成响应'],
    ['node.llmAgentflow.root.label@674900a77b79', 'LLM'],
    ['node.llmAgentflow.root/inputs/llmEnableMemory.description@3b57e4b0594c', '为当前对话线程启用记忆'],
    ['node.llmAgentflow.root/inputs/llmEnableMemory.label@c9cd83363056', '启用记忆'],
    ['node.llmAgentflow.root/inputs/llmMemoryMaxTokenLimit.description@5abdf990bfa7', '达到 Token 上限后对对话进行摘要，默认值为 2000'],
    ['node.llmAgentflow.root/inputs/llmMemoryMaxTokenLimit.label@1dcc214bcf11', '最大 Token 数'],
    ['node.llmAgentflow.root/inputs/llmMemoryType.label@e1236313c834', '记忆类型'],
    ['node.llmAgentflow.root/inputs/llmMemoryType/options/allMessages.description@050924374da0', '获取对话中的全部消息'],
    ['node.llmAgentflow.root/inputs/llmMemoryType/options/allMessages.label@020dc04d5347', '全部消息'],
    ['node.llmAgentflow.root/inputs/llmMemoryType/options/conversationSummary.description@d2752e1fd9c6', '对完整对话进行摘要'],
    ['node.llmAgentflow.root/inputs/llmMemoryType/options/conversationSummary.label@01d3797563b1', '对话摘要'],
    [
        'node.llmAgentflow.root/inputs/llmMemoryType/options/conversationSummaryBuffer.description@5abdf990bfa7',
        '达到 Token 上限后对对话进行摘要，默认值为 2000'
    ],
    ['node.llmAgentflow.root/inputs/llmMemoryType/options/conversationSummaryBuffer.label@9cccef88e094', '对话摘要缓冲区'],
    ['node.llmAgentflow.root/inputs/llmMemoryType/options/windowSize.description@2375b0f0cb00', '使用固定窗口显示最近 N 条消息'],
    ['node.llmAgentflow.root/inputs/llmMemoryType/options/windowSize.label@9010362dc031', '窗口大小'],
    ['node.llmAgentflow.root/inputs/llmMemoryWindowSize.description@2375b0f0cb00', '使用固定窗口显示最近 N 条消息'],
    ['node.llmAgentflow.root/inputs/llmMemoryWindowSize.label@9010362dc031', '窗口大小'],
    ['node.llmAgentflow.root/inputs/llmMessages.label@04d7b4833927', '消息'],
    ['node.llmAgentflow.root/inputs/llmMessages/array/content.label@47bd29075f8b', '内容'],
    ['node.llmAgentflow.root/inputs/llmMessages/array/role.label@14736a2eb9f4', '角色'],
    ['node.llmAgentflow.root/inputs/llmMessages/array/role/options/assistant.label@391e40515277', '助手'],
    ['node.llmAgentflow.root/inputs/llmMessages/array/role/options/developer.label@3fb7b39416f1', '开发者'],
    ['node.llmAgentflow.root/inputs/llmMessages/array/role/options/system.label@6725e7bbcd28', '系统'],
    ['node.llmAgentflow.root/inputs/llmMessages/array/role/options/user.label@b512d97e7cbf', '用户'],
    ['node.llmAgentflow.root/inputs/llmModel.label@5e2c614c23f0', '模型'],
    ['node.llmAgentflow.root/inputs/llmReturnResponseAs.label@ba98ff33219c', '响应返回为'],
    ['node.llmAgentflow.root/inputs/llmReturnResponseAs/options/assistantMessage.label@a23e1001767c', '助手消息'],
    ['node.llmAgentflow.root/inputs/llmReturnResponseAs/options/userMessage.label@fb33af32d694', '用户消息'],
    ['node.llmAgentflow.root/inputs/llmStructuredOutput.description@729105e78146', '指示 LLM 按照 JSON 结构定义输出'],
    ['node.llmAgentflow.root/inputs/llmStructuredOutput.label@5212deb43b7f', 'JSON 结构化输出'],
    ['node.llmAgentflow.root/inputs/llmStructuredOutput/array/description.label@526e0087cc3f', '说明'],
    ['node.llmAgentflow.root/inputs/llmStructuredOutput/array/description.placeholder@c65146c4dfde', '键的说明'],
    ['node.llmAgentflow.root/inputs/llmStructuredOutput/array/enumValues.description@389254c5e32d', '枚举值，使用逗号分隔'],
    ['node.llmAgentflow.root/inputs/llmStructuredOutput/array/enumValues.label@36a902b279bd', '枚举值'],
    ['node.llmAgentflow.root/inputs/llmStructuredOutput/array/enumValues.placeholder@ed8416b4f900', '值1, 值2, 值3'],
    ['node.llmAgentflow.root/inputs/llmStructuredOutput/array/jsonSchema.description@484e1d18142a', '结构化输出所使用的 JSON 架构'],
    ['node.llmAgentflow.root/inputs/llmStructuredOutput/array/jsonSchema.label@13a8f29ba149', 'JSON 架构'],
    [
        'node.llmAgentflow.root/inputs/llmStructuredOutput/array/jsonSchema.placeholder@777f2a412ac4',
        '{\n    "answer": {\n        "type": "string",\n        "description": "答案值"\n    },\n    "reason": {\n        "type": "string",\n        "description": "答案依据"\n    },\n    "optional": {\n        "type": "boolean"\n    },\n    "count": {\n        "type": "number"\n    },\n    "children": {\n        "type": "array",\n        "items": {\n            "type": "object",\n            "properties": {\n                "value": {\n                    "type": "string",\n                    "description": "子项的答案值"\n                }\n            }\n        }\n    }\n}'
    ],
    ['node.llmAgentflow.root/inputs/llmStructuredOutput/array/key.label@99a52df3ff3d', '键'],
    ['node.llmAgentflow.root/inputs/llmStructuredOutput/array/type.label@baaddf70fb5d', '类型'],
    ['node.llmAgentflow.root/inputs/llmStructuredOutput/array/type/options/boolean.label@a066ff921096', '布尔值'],
    ['node.llmAgentflow.root/inputs/llmStructuredOutput/array/type/options/enum.label@54108dafaac5', '枚举'],
    ['node.llmAgentflow.root/inputs/llmStructuredOutput/array/type/options/jsonArray.label@bfbf8f8f40f8', 'JSON 数组'],
    ['node.llmAgentflow.root/inputs/llmStructuredOutput/array/type/options/number.label@bd82cf16699b', '数字'],
    ['node.llmAgentflow.root/inputs/llmStructuredOutput/array/type/options/string.label@b2ef230e7f4f', '字符串'],
    ['node.llmAgentflow.root/inputs/llmStructuredOutput/array/type/options/stringArray.label@73eddd534239', '字符串数组'],
    ['node.llmAgentflow.root/inputs/llmUpdateState.description@e1092381d050', '在工作流执行期间更新运行时状态'],
    ['node.llmAgentflow.root/inputs/llmUpdateState.label@12cccc3a460b', '更新流程状态'],
    ['node.llmAgentflow.root/inputs/llmUpdateState/array/key.label@99a52df3ff3d', '键'],
    ['node.llmAgentflow.root/inputs/llmUpdateState/array/value.label@8e37953d23da', '值'],
    ['node.llmAgentflow.root/inputs/llmUserMessage.description@92396550e25c', '在对话末尾以用户消息形式添加一条输入消息'],
    ['node.llmAgentflow.root/inputs/llmUserMessage.label@333ca21cd322', '输入消息'],
    ['node.startAgentflow.root.description@d0b0af71079b', '智能体流程的起点'],
    ['node.startAgentflow.root.label@e4bb9f1ece9a', '开始'],
    [
        'node.startAgentflow.root/inputs/callbackSecret.description@d6edef8afb9d',
        '可选。设置后，传出的回调 POST 将使用 HMAC-SHA256 签名，并通过 X-Flowise-Signature: sha256=<hex> 传递，以便回调端点验证请求确实来自 Flowise。'
    ],
    ['node.startAgentflow.root/inputs/callbackSecret.label@7fb751f7979a', '回调密钥'],
    [
        'node.startAgentflow.root/inputs/callbackUrl.description@e5d108f3af66',
        '可选。流程完成后，Flowise 会通过 POST 将结果发送到此 URL。留空时采用“触发后不等待”模式：流程仍会在后台运行，但不会发送回调。'
    ],
    ['node.startAgentflow.root/inputs/callbackUrl.label@dc297ae9995b', '回调 URL'],
    ['node.startAgentflow.root/inputs/callbackUrl.placeholder@047439e0da5a', 'https://example.com/flowise-callback'],
    ['node.startAgentflow.root/inputs/formDescription.label@c2e57936e6db', '表单说明'],
    ['node.startAgentflow.root/inputs/formDescription.placeholder@e024d50cbb5f', '请填写下方全部字段后继续'],
    ['node.startAgentflow.root/inputs/formInputTypes.description@600ad6f644bd', '指定表单输入的类型'],
    ['node.startAgentflow.root/inputs/formInputTypes.label@641018f1a609', '表单输入类型'],
    ['node.startAgentflow.root/inputs/formInputTypes/array/addOptions.label@f72e8abaee3d', '添加选项'],
    ['node.startAgentflow.root/inputs/formInputTypes/array/addOptions/array/option.label@45aaacba7ea1', '选项'],
    ['node.startAgentflow.root/inputs/formInputTypes/array/label.label@0e66373f45dc', '标签'],
    ['node.startAgentflow.root/inputs/formInputTypes/array/label.placeholder@5085be3d1c55', '输入项的标签'],
    [
        'node.startAgentflow.root/inputs/formInputTypes/array/name.description@8fb27c4e3b5a',
        '变量名必须使用 camelCase，例如 firstName、lastName 等。'
    ],
    ['node.startAgentflow.root/inputs/formInputTypes/array/name.label@27c2ee034842', '变量名'],
    ['node.startAgentflow.root/inputs/formInputTypes/array/name.placeholder@1e97e046ac41', '输入项的变量名（必须使用 camelCase）'],
    ['node.startAgentflow.root/inputs/formInputTypes/array/type.label@baaddf70fb5d', '类型'],
    ['node.startAgentflow.root/inputs/formInputTypes/array/type/options/boolean.label@a066ff921096', '布尔值'],
    ['node.startAgentflow.root/inputs/formInputTypes/array/type/options/number.label@bd82cf16699b', '数字'],
    ['node.startAgentflow.root/inputs/formInputTypes/array/type/options/options.label@d0db8b5e364b', '选项'],
    ['node.startAgentflow.root/inputs/formInputTypes/array/type/options/string.label@b2ef230e7f4f', '字符串'],
    ['node.startAgentflow.root/inputs/formTitle.label@0654f4c2de1f', '表单标题'],
    ['node.startAgentflow.root/inputs/formTitle.placeholder@39f2ce3b72a9', '请填写表单'],
    [
        'node.startAgentflow.root/inputs/scheduleCronExpression.description@84d3fc4f35e6',
        '标准五字段 Cron 表达式（分钟、小时、日期、月份、星期）。例如，“0 9 * * 1-5”表示每个工作日 09:00 运行。'
    ],
    ['node.startAgentflow.root/inputs/scheduleCronExpression.label@26e53b6c1a78', 'Cron 表达式'],
    ['node.startAgentflow.root/inputs/scheduleCronExpression.placeholder@22b9fd458d10', '0 9 * * 1-5'],
    ['node.startAgentflow.root/inputs/scheduleDefaultInput.description@4a123b6ee5f4', '由调度器触发时传递给流程的默认问题或输入。'],
    ['node.startAgentflow.root/inputs/scheduleDefaultInput.label@bb4b96067a42', '默认输入'],
    ['node.startAgentflow.root/inputs/scheduleDefaultInput.placeholder@af70f4f9a4fa', '运行每日报告'],
    ['node.startAgentflow.root/inputs/scheduleEndDate.description@1b0c006066aa', '可选。超过该日期后，调度计划将停止触发。'],
    ['node.startAgentflow.root/inputs/scheduleEndDate.label@e970951cfb6b', '结束日期'],
    [
        'node.startAgentflow.root/inputs/scheduleFormDefaults.description@c841b9a49717',
        '上方表单字段的默认值，以变量名为键的 JSON 对象表示。例如：{ "team": "engineering", "metric": "p95" }'
    ],
    ['node.startAgentflow.root/inputs/scheduleFormDefaults.label@a55a91d77c54', '默认表单值'],
    ['node.startAgentflow.root/inputs/scheduleFormInputTypes.description@88d38f1b5456', '定义此定时流程每次触发时接收的类型化字段。'],
    ['node.startAgentflow.root/inputs/scheduleFormInputTypes.label@842a4eef5631', '表单字段'],
    ['node.startAgentflow.root/inputs/scheduleFormInputTypes/array/addOptions.label@f72e8abaee3d', '添加选项'],
    ['node.startAgentflow.root/inputs/scheduleFormInputTypes/array/addOptions/array/option.label@45aaacba7ea1', '选项'],
    ['node.startAgentflow.root/inputs/scheduleFormInputTypes/array/label.label@0e66373f45dc', '标签'],
    ['node.startAgentflow.root/inputs/scheduleFormInputTypes/array/label.placeholder@5085be3d1c55', '输入项的标签'],
    [
        'node.startAgentflow.root/inputs/scheduleFormInputTypes/array/name.description@8fb27c4e3b5a',
        '变量名必须使用 camelCase，例如 firstName、lastName 等。'
    ],
    ['node.startAgentflow.root/inputs/scheduleFormInputTypes/array/name.label@27c2ee034842', '变量名'],
    ['node.startAgentflow.root/inputs/scheduleFormInputTypes/array/name.placeholder@1e97e046ac41', '输入项的变量名（必须使用 camelCase）'],
    ['node.startAgentflow.root/inputs/scheduleFormInputTypes/array/type.label@baaddf70fb5d', '类型'],
    ['node.startAgentflow.root/inputs/scheduleFormInputTypes/array/type/options/boolean.label@a066ff921096', '布尔值'],
    ['node.startAgentflow.root/inputs/scheduleFormInputTypes/array/type/options/number.label@bd82cf16699b', '数字'],
    ['node.startAgentflow.root/inputs/scheduleFormInputTypes/array/type/options/options.label@d0db8b5e364b', '选项'],
    ['node.startAgentflow.root/inputs/scheduleFormInputTypes/array/type/options/string.label@b2ef230e7f4f', '字符串'],
    ['node.startAgentflow.root/inputs/scheduleFrequency.label@16b6668d9831', '频率'],
    ['node.startAgentflow.root/inputs/scheduleFrequency/options/daily.description@b5ec4a4ef1e4', '每天在指定时间运行'],
    ['node.startAgentflow.root/inputs/scheduleFrequency/options/daily.label@b36c2611dcdf', '每天'],
    ['node.startAgentflow.root/inputs/scheduleFrequency/options/hourly.description@f197c723c1c0', '每小时在指定时间运行'],
    ['node.startAgentflow.root/inputs/scheduleFrequency/options/hourly.label@eab0cd8fdf9b', '每小时'],
    ['node.startAgentflow.root/inputs/scheduleFrequency/options/monthly.description@c014140d2639', '每月在指定日期和时间运行'],
    ['node.startAgentflow.root/inputs/scheduleFrequency/options/monthly.label@9b11f6b707d2', '每月'],
    ['node.startAgentflow.root/inputs/scheduleFrequency/options/weekly.description@21116e2e8862', '每周在指定星期和时间运行'],
    ['node.startAgentflow.root/inputs/scheduleFrequency/options/weekly.label@2975132481a7', '每周'],
    ['node.startAgentflow.root/inputs/scheduleInputMode.description@78858c6007b3', '调度计划每次触发时调用此流程的方式。'],
    ['node.startAgentflow.root/inputs/scheduleInputMode.label@0ce3ec505748', '定时输入模式'],
    ['node.startAgentflow.root/inputs/scheduleInputMode/options/form.description@cbe822edc8da', '每次触发时传入下方表单字段的默认值'],
    ['node.startAgentflow.root/inputs/scheduleInputMode/options/form.label@7fa34ae3166c', '表单输入'],
    ['node.startAgentflow.root/inputs/scheduleInputMode/options/none.description@6fc479319454', '触发时不传入任何输入。'],
    ['node.startAgentflow.root/inputs/scheduleInputMode/options/none.label@3980333069ba', '无输入'],
    ['node.startAgentflow.root/inputs/scheduleInputMode/options/text.description@3b24c59065c1', '每次触发时将固定文本字符串作为问题传入'],
    ['node.startAgentflow.root/inputs/scheduleInputMode/options/text.label@6c377194bb2b', '默认文本输入'],
    ['node.startAgentflow.root/inputs/scheduleOnDayOfMonth.label@d555c6f8d3c6', '每月日期'],
    ['node.startAgentflow.root/inputs/scheduleOnDayOfWeek.label@9071fc52ceab', '星期'],
    [
        'node.startAgentflow.root/inputs/scheduleOnMinute.description@4b0024b4d98c',
        '调度计划在每小时的第几分钟运行（0–59）。例如，“30”表示在每小时第 30 分钟运行。'
    ],
    ['node.startAgentflow.root/inputs/scheduleOnMinute.label@ef1f8163de42', '分钟'],
    ['node.startAgentflow.root/inputs/scheduleOnMinute.placeholder@624b60c58c9d', '30'],
    ['node.startAgentflow.root/inputs/scheduleOnTime.label@64cd02224f1c', '时间'],
    ['node.startAgentflow.root/inputs/scheduleTimezone.description@141f5e314b0c', 'IANA 时区，默认为 UTC。'],
    ['node.startAgentflow.root/inputs/scheduleTimezone.label@4ceca1d52ced', '时区'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Abidjan.label@8e9e0533acc5', 'Africa/Abidjan'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Accra.label@413c61b75c17', 'Africa/Accra'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Addis_Ababa.label@441ada017217', 'Africa/Addis_Ababa'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Algiers.label@a011131551bd', 'Africa/Algiers'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Asmera.label@eab3966cb189', 'Africa/Asmera'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Bamako.label@c7c63329217f', 'Africa/Bamako'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Bangui.label@886e7fd3eee8', 'Africa/Bangui'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Banjul.label@fbeba3a5ec59', 'Africa/Banjul'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Bissau.label@467771c29cd7', 'Africa/Bissau'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Blantyre.label@6d19c74920d6', 'Africa/Blantyre'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Brazzaville.label@e73e6efe2a81', 'Africa/Brazzaville'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Bujumbura.label@45ceddf2f828', 'Africa/Bujumbura'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Cairo.label@2e9a9bb3cc43', 'Africa/Cairo'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Casablanca.label@9824257c811f', 'Africa/Casablanca'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Ceuta.label@25e1c8312600', 'Africa/Ceuta'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Conakry.label@573b6836c1f9', 'Africa/Conakry'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Dakar.label@47302d2c6d23', 'Africa/Dakar'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Dar_es_Salaam.label@8bedeb39bc6d', 'Africa/Dar_es_Salaam'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Djibouti.label@9da4c7b42901', 'Africa/Djibouti'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Douala.label@68e4f331b314', 'Africa/Douala'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1El_Aaiun.label@39923d61d961', 'Africa/El_Aaiun'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Freetown.label@957ec0de24ed', 'Africa/Freetown'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Gaborone.label@bf7846ff85a6', 'Africa/Gaborone'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Harare.label@ac504bd693c0', 'Africa/Harare'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Johannesburg.label@cc7db809992d', 'Africa/Johannesburg'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Juba.label@3b62a8622715', 'Africa/Juba'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Kampala.label@84634579fea5', 'Africa/Kampala'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Khartoum.label@e9e3b0177711', 'Africa/Khartoum'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Kigali.label@f32e5b5922d8', 'Africa/Kigali'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Kinshasa.label@94e722c4a361', 'Africa/Kinshasa'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Lagos.label@93ba6a132553', 'Africa/Lagos'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Libreville.label@8fd743d7caf5', 'Africa/Libreville'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Lome.label@788aab353fcc', 'Africa/Lome'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Luanda.label@448b74968f80', 'Africa/Luanda'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Lubumbashi.label@1b902fa1eb2f', 'Africa/Lubumbashi'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Lusaka.label@e7cc2eb182c0', 'Africa/Lusaka'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Malabo.label@ec05bc313319', 'Africa/Malabo'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Maputo.label@8050abe3fb4b', 'Africa/Maputo'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Maseru.label@baca8339847c', 'Africa/Maseru'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Mbabane.label@90e6efc1953e', 'Africa/Mbabane'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Mogadishu.label@e8dc340bb241', 'Africa/Mogadishu'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Monrovia.label@c27f4f2d4130', 'Africa/Monrovia'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Nairobi.label@8a46a5b88726', 'Africa/Nairobi'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Ndjamena.label@53dbf03db9e7', 'Africa/Ndjamena'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Niamey.label@4c4c3af4718e', 'Africa/Niamey'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Nouakchott.label@f94c4a85f189', 'Africa/Nouakchott'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Ouagadougou.label@85ebcfb3d381', 'Africa/Ouagadougou'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Porto-Novo.label@b4677dd13ead', 'Africa/Porto-Novo'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Sao_Tome.label@921e22e0c226', 'Africa/Sao_Tome'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Tripoli.label@77e271871238', 'Africa/Tripoli'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Tunis.label@6dbca29ce898', 'Africa/Tunis'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Africa~1Windhoek.label@507df7b946af', 'Africa/Windhoek'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Adak.label@3e1e07e40908', 'America/Adak'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Anchorage.label@d6bd4d6652b2', 'America/Anchorage'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Anguilla.label@4f89952748d9', 'America/Anguilla'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Antigua.label@0300c9b6089b', 'America/Antigua'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Araguaina.label@812dea334a55', 'America/Araguaina'],
    [
        'node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Argentina~1La_Rioja.label@9bbec736626a',
        'America/Argentina/La_Rioja'
    ],
    [
        'node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Argentina~1Rio_Gallegos.label@49e12d393177',
        'America/Argentina/Rio_Gallegos'
    ],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Argentina~1Salta.label@25ed1c53b630', 'America/Argentina/Salta'],
    [
        'node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Argentina~1San_Juan.label@3feda1eb0909',
        'America/Argentina/San_Juan'
    ],
    [
        'node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Argentina~1San_Luis.label@44c9bd0297f2',
        'America/Argentina/San_Luis'
    ],
    [
        'node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Argentina~1Tucuman.label@908883d0e43f',
        'America/Argentina/Tucuman'
    ],
    [
        'node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Argentina~1Ushuaia.label@9a6ca963dc13',
        'America/Argentina/Ushuaia'
    ],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Aruba.label@c8d9bcf7660d', 'America/Aruba'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Asuncion.label@8ca340d8332b', 'America/Asuncion'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Bahia_Banderas.label@27414574ddea', 'America/Bahia_Banderas'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Bahia.label@4bcf2327bdfa', 'America/Bahia'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Barbados.label@f985cbcbd04e', 'America/Barbados'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Belem.label@edf73aebb050', 'America/Belem'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Belize.label@24381ca5e584', 'America/Belize'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Blanc-Sablon.label@0c61ac7b3ee6', 'America/Blanc-Sablon'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Boa_Vista.label@255f16ab6c19', 'America/Boa_Vista'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Bogota.label@43a0373f2cad', 'America/Bogota'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Boise.label@4d8533a4cf39', 'America/Boise'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Buenos_Aires.label@de332c0b5d4f', 'America/Buenos_Aires'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Cambridge_Bay.label@e6383dcfed6a', 'America/Cambridge_Bay'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Campo_Grande.label@8f550bbe6745', 'America/Campo_Grande'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Cancun.label@d146e1f1fc88', 'America/Cancun'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Caracas.label@7eb53a2fe44e', 'America/Caracas'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Catamarca.label@fe455d824719', 'America/Catamarca'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Cayenne.label@cc347c64f74d', 'America/Cayenne'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Cayman.label@75780bdb313a', 'America/Cayman'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Chicago.label@a77b7136d7ec', 'America/Chicago'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Chihuahua.label@8c39ea6b0ab4', 'America/Chihuahua'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Ciudad_Juarez.label@9ea93bcc219e', 'America/Ciudad_Juarez'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Coral_Harbour.label@d9b2e65a0a7c', 'America/Coral_Harbour'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Cordoba.label@f36baeb999c8', 'America/Cordoba'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Costa_Rica.label@4fddfbc439b7', 'America/Costa_Rica'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Coyhaique.label@10e97bb5a148', 'America/Coyhaique'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Creston.label@bf88544b926f', 'America/Creston'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Cuiaba.label@5ebaa1ca743c', 'America/Cuiaba'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Curacao.label@0166b5e29984', 'America/Curacao'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Danmarkshavn.label@d1a448a62d1f', 'America/Danmarkshavn'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Dawson_Creek.label@12d02d2d9a13', 'America/Dawson_Creek'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Dawson.label@650a86e5095b', 'America/Dawson'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Denver.label@9e36365b2f6c', 'America/Denver'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Detroit.label@034883cbbcdc', 'America/Detroit'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Dominica.label@6d6eade7ca6c', 'America/Dominica'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Edmonton.label@58f2f20328fc', 'America/Edmonton'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Eirunepe.label@6ac36e16b231', 'America/Eirunepe'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1El_Salvador.label@40e46ad3f9f2', 'America/El_Salvador'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Fort_Nelson.label@3a65ddfba767', 'America/Fort_Nelson'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Fortaleza.label@1dc70db68b2b', 'America/Fortaleza'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Glace_Bay.label@b4c48e5a8ca1', 'America/Glace_Bay'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Godthab.label@5e8c06da3feb', 'America/Godthab'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Goose_Bay.label@e5b7d173692b', 'America/Goose_Bay'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Grand_Turk.label@b10832f70be4', 'America/Grand_Turk'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Grenada.label@fa99bd35c952', 'America/Grenada'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Guadeloupe.label@8f7b5f1a5bb2', 'America/Guadeloupe'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Guatemala.label@83e28b1c7cce', 'America/Guatemala'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Guayaquil.label@2bb9c2965be3', 'America/Guayaquil'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Guyana.label@94e1ec24f64a', 'America/Guyana'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Halifax.label@9958a325c3e3', 'America/Halifax'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Havana.label@0093ef77adba', 'America/Havana'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Hermosillo.label@7bd503343f83', 'America/Hermosillo'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Indiana~1Knox.label@a7c2845512f2', 'America/Indiana/Knox'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Indiana~1Marengo.label@305c1736bbb9', 'America/Indiana/Marengo'],
    [
        'node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Indiana~1Petersburg.label@11e160f8fc01',
        'America/Indiana/Petersburg'
    ],
    [
        'node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Indiana~1Tell_City.label@32a6efd42db8',
        'America/Indiana/Tell_City'
    ],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Indiana~1Vevay.label@9a85937e48c4', 'America/Indiana/Vevay'],
    [
        'node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Indiana~1Vincennes.label@1d3d116d624b',
        'America/Indiana/Vincennes'
    ],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Indiana~1Winamac.label@42867a562873', 'America/Indiana/Winamac'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Indianapolis.label@e2e9e4be9067', 'America/Indianapolis'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Inuvik.label@51299c7c76af', 'America/Inuvik'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Iqaluit.label@a841c860c902', 'America/Iqaluit'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Jamaica.label@390566b0d523', 'America/Jamaica'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Jujuy.label@61088ae4575f', 'America/Jujuy'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Juneau.label@64a28b6ab0f8', 'America/Juneau'],
    [
        'node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Kentucky~1Monticello.label@31671ebd2d16',
        'America/Kentucky/Monticello'
    ],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Kralendijk.label@6fd0ae0167c9', 'America/Kralendijk'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1La_Paz.label@c5680a19e2f9', 'America/La_Paz'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Lima.label@d4914fc8e52f', 'America/Lima'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Los_Angeles.label@2d4bbedff807', 'America/Los_Angeles'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Louisville.label@55d8537d0b34', 'America/Louisville'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Lower_Princes.label@e6bfe941e700', 'America/Lower_Princes'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Maceio.label@2b4b52ed6662', 'America/Maceio'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Managua.label@cab62ce00581', 'America/Managua'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Manaus.label@e42c8b46eba6', 'America/Manaus'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Marigot.label@ad2ca32e3871', 'America/Marigot'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Martinique.label@7d07c17a6465', 'America/Martinique'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Matamoros.label@1535ac2efbde', 'America/Matamoros'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Mazatlan.label@021bd35a0bd2', 'America/Mazatlan'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Mendoza.label@5571547492b5', 'America/Mendoza'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Menominee.label@65e393f664b1', 'America/Menominee'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Merida.label@5df6de9cb5ac', 'America/Merida'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Metlakatla.label@e6e6dae1f34f', 'America/Metlakatla'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Mexico_City.label@fd8d3b93c3d8', 'America/Mexico_City'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Miquelon.label@0717decf4459', 'America/Miquelon'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Moncton.label@b3215ec38257', 'America/Moncton'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Monterrey.label@4e6c351c76ec', 'America/Monterrey'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Montevideo.label@51ffc663078e', 'America/Montevideo'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Montserrat.label@1664fbe26abb', 'America/Montserrat'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Nassau.label@ee0edae093f3', 'America/Nassau'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1New_York.label@acb2a3287bc6', 'America/New_York'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Nome.label@5d8d80c8d91c', 'America/Nome'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Noronha.label@5e83381a8e49', 'America/Noronha'],
    [
        'node.startAgentflow.root/inputs/scheduleTimezone/options/America~1North_Dakota~1Beulah.label@044bb9faa92e',
        'America/North_Dakota/Beulah'
    ],
    [
        'node.startAgentflow.root/inputs/scheduleTimezone/options/America~1North_Dakota~1Center.label@ba741b26bdbf',
        'America/North_Dakota/Center'
    ],
    [
        'node.startAgentflow.root/inputs/scheduleTimezone/options/America~1North_Dakota~1New_Salem.label@603cceed3698',
        'America/North_Dakota/New_Salem'
    ],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Ojinaga.label@a6bec8fb1b37', 'America/Ojinaga'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Panama.label@5008245115c3', 'America/Panama'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Paramaribo.label@5a046b252eab', 'America/Paramaribo'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Phoenix.label@b919121b45ae', 'America/Phoenix'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Port_of_Spain.label@d389d35d9924', 'America/Port_of_Spain'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Port-au-Prince.label@165528b666cd', 'America/Port-au-Prince'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Porto_Velho.label@a1e5ce5a6fa2', 'America/Porto_Velho'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Puerto_Rico.label@c8e719bdfece', 'America/Puerto_Rico'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Punta_Arenas.label@bf893bd53aba', 'America/Punta_Arenas'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Rankin_Inlet.label@ffb2a4357131', 'America/Rankin_Inlet'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Recife.label@7dd4d6f32ecd', 'America/Recife'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Regina.label@24c66d1bae70', 'America/Regina'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Resolute.label@a2d15c87291f', 'America/Resolute'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Rio_Branco.label@e3b87ba408d1', 'America/Rio_Branco'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Santarem.label@a7581d3c3f67', 'America/Santarem'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Santiago.label@58c885a79d98', 'America/Santiago'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Santo_Domingo.label@f1c0a3eb2c29', 'America/Santo_Domingo'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Sao_Paulo.label@53e24af00e96', 'America/Sao_Paulo'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Scoresbysund.label@4c5d2fd44a2b', 'America/Scoresbysund'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Sitka.label@a62ed7605f1f', 'America/Sitka'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1St_Barthelemy.label@d6b47c700f1d', 'America/St_Barthelemy'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1St_Johns.label@7aae522a697e', 'America/St_Johns'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1St_Kitts.label@08a0e68352ca', 'America/St_Kitts'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1St_Lucia.label@70a9ef58820b', 'America/St_Lucia'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1St_Thomas.label@88b067a46e35', 'America/St_Thomas'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1St_Vincent.label@27838240d160', 'America/St_Vincent'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Swift_Current.label@d56db9f453ad', 'America/Swift_Current'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Tegucigalpa.label@da21eb2c2af5', 'America/Tegucigalpa'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Thule.label@e9ff957d161f', 'America/Thule'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Tijuana.label@73a0af6b24ca', 'America/Tijuana'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Toronto.label@feaa40fb2ab0', 'America/Toronto'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Tortola.label@690111cb72de', 'America/Tortola'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Vancouver.label@9e906781f47b', 'America/Vancouver'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Whitehorse.label@1813c1b86f1a', 'America/Whitehorse'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Winnipeg.label@05551849429f', 'America/Winnipeg'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/America~1Yakutat.label@90f715c40f64', 'America/Yakutat'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Antarctica~1Casey.label@0c4b851a6bcd', 'Antarctica/Casey'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Antarctica~1Davis.label@871eeaa9d9f7', 'Antarctica/Davis'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Antarctica~1DumontDUrville.label@e5a2f75d2ae8', 'Antarctica/DumontDUrville'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Antarctica~1Macquarie.label@f4296b077466', 'Antarctica/Macquarie'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Antarctica~1Mawson.label@c36592a27bd5', 'Antarctica/Mawson'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Antarctica~1McMurdo.label@bd1de2d0b576', 'Antarctica/McMurdo'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Antarctica~1Palmer.label@8d00e16a35ea', 'Antarctica/Palmer'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Antarctica~1Rothera.label@06aa1cba95d0', 'Antarctica/Rothera'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Antarctica~1Syowa.label@b2d49028a72a', 'Antarctica/Syowa'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Antarctica~1Troll.label@0c9c095685c4', 'Antarctica/Troll'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Antarctica~1Vostok.label@76bc8cbfd5cf', 'Antarctica/Vostok'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Arctic~1Longyearbyen.label@54b242086569', 'Arctic/Longyearbyen'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Aden.label@49b113954422', 'Asia/Aden'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Almaty.label@7bb2ce5e75a6', 'Asia/Almaty'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Amman.label@07e1927c3b8a', 'Asia/Amman'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Anadyr.label@add02c73b19b', 'Asia/Anadyr'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Aqtau.label@d247a085ce34', 'Asia/Aqtau'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Aqtobe.label@1a92c723b322', 'Asia/Aqtobe'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Ashgabat.label@8d3bcac67cfe', 'Asia/Ashgabat'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Atyrau.label@838f380d4b8b', 'Asia/Atyrau'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Baghdad.label@cc688922b818', 'Asia/Baghdad'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Bahrain.label@bef0674680dc', 'Asia/Bahrain'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Baku.label@9818606cf4e6', 'Asia/Baku'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Bangkok.label@e8def3265620', 'Asia/Bangkok'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Barnaul.label@e20e3f9d1d81', 'Asia/Barnaul'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Beirut.label@47d69d9dd207', 'Asia/Beirut'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Bishkek.label@5d78121fd728', 'Asia/Bishkek'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Brunei.label@0c0ef577e60c', 'Asia/Brunei'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Calcutta.label@7d75e0ca00d3', 'Asia/Calcutta'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Chita.label@a241cf7f6370', 'Asia/Chita'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Colombo.label@aa94105757d7', 'Asia/Colombo'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Damascus.label@dcc4971cdc69', 'Asia/Damascus'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Dhaka.label@d2342499eace', 'Asia/Dhaka'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Dili.label@75316c5b67ab', 'Asia/Dili'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Dubai.label@0cc1a975a27f', 'Asia/Dubai'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Dushanbe.label@848f466449ef', 'Asia/Dushanbe'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Famagusta.label@2ba671b3c31c', 'Asia/Famagusta'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Gaza.label@e46bcf0835cc', 'Asia/Gaza'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Hebron.label@25db61671916', 'Asia/Hebron'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Hong_Kong.label@806bf04c18f6', 'Asia/Hong_Kong'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Hovd.label@ebfe57946e63', 'Asia/Hovd'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Irkutsk.label@db273b1692c3', 'Asia/Irkutsk'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Jakarta.label@3b647dcf9395', 'Asia/Jakarta'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Jayapura.label@ba4c08f61f98', 'Asia/Jayapura'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Jerusalem.label@767f41f54793', 'Asia/Jerusalem'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Kabul.label@d87850b9aacf', 'Asia/Kabul'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Kamchatka.label@81a0aa047b39', 'Asia/Kamchatka'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Karachi.label@770c7a71851b', 'Asia/Karachi'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Katmandu.label@4c11aad347e3', 'Asia/Katmandu'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Khandyga.label@5e4017671a41', 'Asia/Khandyga'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Krasnoyarsk.label@6893f45dd7fd', 'Asia/Krasnoyarsk'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Kuala_Lumpur.label@645a6c2bba2c', 'Asia/Kuala_Lumpur'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Kuching.label@d67f3550bbde', 'Asia/Kuching'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Kuwait.label@17365c6a10da', 'Asia/Kuwait'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Macau.label@d9151dea2b8c', 'Asia/Macau'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Magadan.label@1a8ae99a2a27', 'Asia/Magadan'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Makassar.label@107dc25fa434', 'Asia/Makassar'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Manila.label@c84dc54b6fda', 'Asia/Manila'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Muscat.label@f118fca9ad29', 'Asia/Muscat'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Nicosia.label@2f4fa03de437', 'Asia/Nicosia'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Novokuznetsk.label@ec2ef7946ba7', 'Asia/Novokuznetsk'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Novosibirsk.label@9021e880363f', 'Asia/Novosibirsk'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Omsk.label@41964ca79232', 'Asia/Omsk'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Oral.label@6ec81cffbf80', 'Asia/Oral'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Phnom_Penh.label@1f6756a1868e', 'Asia/Phnom_Penh'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Pontianak.label@115332ec7eb2', 'Asia/Pontianak'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Pyongyang.label@8ccdf05936ed', 'Asia/Pyongyang'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Qatar.label@796751c31e4e', 'Asia/Qatar'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Qostanay.label@2b144db819ac', 'Asia/Qostanay'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Qyzylorda.label@f9e0ffbe492c', 'Asia/Qyzylorda'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Rangoon.label@d1f17e72a70e', 'Asia/Rangoon'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Riyadh.label@c80ce74da80b', 'Asia/Riyadh'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Saigon.label@ffbd7b4dc45c', 'Asia/Saigon'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Sakhalin.label@535c83421f18', 'Asia/Sakhalin'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Samarkand.label@70e109f9b0cf', 'Asia/Samarkand'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Seoul.label@a8a5fc7a91cc', 'Asia/Seoul'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Shanghai.label@95033d34e64e', 'Asia/Shanghai'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Singapore.label@4b773e48c663', 'Asia/Singapore'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Srednekolymsk.label@81137566bab0', 'Asia/Srednekolymsk'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Taipei.label@2feef03a36ac', 'Asia/Taipei'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Tashkent.label@10c5bc983a82', 'Asia/Tashkent'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Tbilisi.label@ce4cfb476450', 'Asia/Tbilisi'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Tehran.label@23f12ca4e3cb', 'Asia/Tehran'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Thimphu.label@dd81f1803812', 'Asia/Thimphu'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Tokyo.label@d03f5792f1d2', 'Asia/Tokyo'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Tomsk.label@107d73d97f72', 'Asia/Tomsk'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Ulaanbaatar.label@5a0e82625e24', 'Asia/Ulaanbaatar'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Urumqi.label@85f5a295ad09', 'Asia/Urumqi'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Ust-Nera.label@7bb0a84ba4d8', 'Asia/Ust-Nera'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Vientiane.label@c286c8838348', 'Asia/Vientiane'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Vladivostok.label@126d3da5a620', 'Asia/Vladivostok'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Yakutsk.label@85f2e910aedb', 'Asia/Yakutsk'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Yekaterinburg.label@2e7a548ea689', 'Asia/Yekaterinburg'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Asia~1Yerevan.label@1e8a75a85f5c', 'Asia/Yerevan'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Atlantic~1Azores.label@c17e63e7a477', 'Atlantic/Azores'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Atlantic~1Bermuda.label@f77d33c2e783', 'Atlantic/Bermuda'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Atlantic~1Canary.label@8d56d8ca5a18', 'Atlantic/Canary'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Atlantic~1Cape_Verde.label@c019f8289185', 'Atlantic/Cape_Verde'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Atlantic~1Faeroe.label@283e2082acb9', 'Atlantic/Faeroe'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Atlantic~1Madeira.label@686b7ddda917', 'Atlantic/Madeira'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Atlantic~1Reykjavik.label@7528488f12ad', 'Atlantic/Reykjavik'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Atlantic~1South_Georgia.label@4d91d7e278f4', 'Atlantic/South_Georgia'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Atlantic~1St_Helena.label@e85c65f96e21', 'Atlantic/St_Helena'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Atlantic~1Stanley.label@4c05bf0a896f', 'Atlantic/Stanley'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Australia~1Adelaide.label@16a54973c8f7', 'Australia/Adelaide'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Australia~1Brisbane.label@3db6e5843d96', 'Australia/Brisbane'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Australia~1Broken_Hill.label@6ceb80996c2e', 'Australia/Broken_Hill'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Australia~1Darwin.label@234962e6dc34', 'Australia/Darwin'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Australia~1Eucla.label@5727028491e6', 'Australia/Eucla'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Australia~1Hobart.label@81f6690a0c58', 'Australia/Hobart'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Australia~1Lindeman.label@f1d0d2f82943', 'Australia/Lindeman'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Australia~1Lord_Howe.label@b26eee0e505b', 'Australia/Lord_Howe'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Australia~1Melbourne.label@a78ce7fd38bc', 'Australia/Melbourne'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Australia~1Perth.label@825144946a6b', 'Australia/Perth'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Australia~1Sydney.label@b27b602aa501', 'Australia/Sydney'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Amsterdam.label@c147c70a2945', 'Europe/Amsterdam'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Andorra.label@f7385fce0752', 'Europe/Andorra'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Astrakhan.label@c501ce72071b', 'Europe/Astrakhan'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Athens.label@95cf9c255a8e', 'Europe/Athens'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Belgrade.label@d843670b72bb', 'Europe/Belgrade'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Berlin.label@99f0b5e419f7', 'Europe/Berlin'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Bratislava.label@5ab4a43c9d1b', 'Europe/Bratislava'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Brussels.label@09a81d6661e5', 'Europe/Brussels'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Bucharest.label@af7cd0f919c0', 'Europe/Bucharest'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Budapest.label@e96c0a8575b7', 'Europe/Budapest'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Busingen.label@a1389738cacf', 'Europe/Busingen'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Chisinau.label@84509ac07b3c', 'Europe/Chisinau'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Copenhagen.label@9f73c87f1649', 'Europe/Copenhagen'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Dublin.label@054efa5769e8', 'Europe/Dublin'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Gibraltar.label@23f9eb35910a', 'Europe/Gibraltar'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Guernsey.label@2ec9443d6aae', 'Europe/Guernsey'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Helsinki.label@916b96b26aae', 'Europe/Helsinki'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Isle_of_Man.label@4ee77649b42a', 'Europe/Isle_of_Man'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Istanbul.label@29085b405b36', 'Europe/Istanbul'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Jersey.label@77cad2aa484f', 'Europe/Jersey'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Kaliningrad.label@f7caa0a98c2b', 'Europe/Kaliningrad'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Kiev.label@099d2adb7f9a', 'Europe/Kiev'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Kirov.label@939cbccf4227', 'Europe/Kirov'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Lisbon.label@aecadecb62cd', 'Europe/Lisbon'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Ljubljana.label@c6ecaa19d283', 'Europe/Ljubljana'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1London.label@d851b36dde76', 'Europe/London'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Luxembourg.label@00ce06071085', 'Europe/Luxembourg'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Madrid.label@078cabaede7e', 'Europe/Madrid'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Malta.label@3918de644fa3', 'Europe/Malta'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Mariehamn.label@80eda2e80028', 'Europe/Mariehamn'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Minsk.label@6efc4d56df0f', 'Europe/Minsk'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Monaco.label@79da1c56a2a0', 'Europe/Monaco'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Moscow.label@cf6de567b837', 'Europe/Moscow'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Oslo.label@7c5749b6432a', 'Europe/Oslo'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Paris.label@cc31b47c7e35', 'Europe/Paris'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Podgorica.label@f0ff7b88cdf8', 'Europe/Podgorica'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Prague.label@abed61aed76e', 'Europe/Prague'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Riga.label@e1a7cd365eb9', 'Europe/Riga'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Rome.label@180c6afadacf', 'Europe/Rome'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Samara.label@74c81269112d', 'Europe/Samara'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1San_Marino.label@b7519296d6d5', 'Europe/San_Marino'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Sarajevo.label@9f3e3d844105', 'Europe/Sarajevo'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Saratov.label@f99ef02ad92d', 'Europe/Saratov'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Simferopol.label@eecdfc63db1b', 'Europe/Simferopol'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Skopje.label@3b7d54d1d3d2', 'Europe/Skopje'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Sofia.label@5be14a299ae9', 'Europe/Sofia'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Stockholm.label@e5a2653e2f23', 'Europe/Stockholm'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Tallinn.label@4ee3d567cef1', 'Europe/Tallinn'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Tirane.label@0a3c659cc7bd', 'Europe/Tirane'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Ulyanovsk.label@84e65db711ca', 'Europe/Ulyanovsk'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Vaduz.label@8dfc0c7b9491', 'Europe/Vaduz'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Vatican.label@b6a92c3787b5', 'Europe/Vatican'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Vienna.label@3db791fb847a', 'Europe/Vienna'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Vilnius.label@90310add4f39', 'Europe/Vilnius'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Volgograd.label@ef0ef114b72e', 'Europe/Volgograd'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Warsaw.label@4b772ed0d26e', 'Europe/Warsaw'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Zagreb.label@22029f966ab8', 'Europe/Zagreb'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Europe~1Zurich.label@650575e62b1f', 'Europe/Zurich'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Indian~1Antananarivo.label@2c45287ca139', 'Indian/Antananarivo'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Indian~1Chagos.label@46794869967e', 'Indian/Chagos'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Indian~1Christmas.label@063a8f5b1f7f', 'Indian/Christmas'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Indian~1Cocos.label@f6674d53ca79', 'Indian/Cocos'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Indian~1Comoro.label@74f9d1524bfd', 'Indian/Comoro'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Indian~1Kerguelen.label@dad832611a00', 'Indian/Kerguelen'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Indian~1Mahe.label@419803fd1d1d', 'Indian/Mahe'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Indian~1Maldives.label@7a51d39fbbc4', 'Indian/Maldives'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Indian~1Mauritius.label@9843bc0435d2', 'Indian/Mauritius'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Indian~1Mayotte.label@b90734cfef01', 'Indian/Mayotte'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Indian~1Reunion.label@5bdc6ddba562', 'Indian/Reunion'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Apia.label@b122ecf95cdb', 'Pacific/Apia'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Auckland.label@d73daf5e9fd9', 'Pacific/Auckland'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Bougainville.label@63b89424d179', 'Pacific/Bougainville'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Chatham.label@b6a0c2c5d47e', 'Pacific/Chatham'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Easter.label@521a5bf45da8', 'Pacific/Easter'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Efate.label@57a73edc8029', 'Pacific/Efate'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Enderbury.label@68b7bd614d01', 'Pacific/Enderbury'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Fakaofo.label@139d48448805', 'Pacific/Fakaofo'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Fiji.label@c305cdf6f1e0', 'Pacific/Fiji'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Funafuti.label@01087200ea0b', 'Pacific/Funafuti'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Galapagos.label@159614fcc966', 'Pacific/Galapagos'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Gambier.label@293890809aa9', 'Pacific/Gambier'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Guadalcanal.label@3ca9875e5644', 'Pacific/Guadalcanal'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Guam.label@0ab36cecf779', 'Pacific/Guam'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Honolulu.label@4c7b9db133f6', 'Pacific/Honolulu'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Kiritimati.label@11e0463b0516', 'Pacific/Kiritimati'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Kosrae.label@ff28fb2d76ad', 'Pacific/Kosrae'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Kwajalein.label@d5f17024c40f', 'Pacific/Kwajalein'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Majuro.label@041fdd204d42', 'Pacific/Majuro'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Marquesas.label@439523787d94', 'Pacific/Marquesas'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Midway.label@5dd10bf23bf7', 'Pacific/Midway'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Nauru.label@94c06fa864ae', 'Pacific/Nauru'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Niue.label@2a769964df03', 'Pacific/Niue'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Norfolk.label@7c0a07fd08f5', 'Pacific/Norfolk'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Noumea.label@954538862c9c', 'Pacific/Noumea'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Pago_Pago.label@89642594f786', 'Pacific/Pago_Pago'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Palau.label@ba881f5b96c0', 'Pacific/Palau'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Pitcairn.label@b0c1adb711d1', 'Pacific/Pitcairn'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Ponape.label@e72829e89be1', 'Pacific/Ponape'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Port_Moresby.label@1f32297e91f2', 'Pacific/Port_Moresby'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Rarotonga.label@9a1047399b54', 'Pacific/Rarotonga'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Saipan.label@43b465f39cfa', 'Pacific/Saipan'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Tahiti.label@f1476a03bd08', 'Pacific/Tahiti'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Tarawa.label@4c5bd835eeb6', 'Pacific/Tarawa'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Tongatapu.label@e9c095f8e1ca', 'Pacific/Tongatapu'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Truk.label@807f83f1cf79', 'Pacific/Truk'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Wake.label@2d650fe51ff0', 'Pacific/Wake'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/Pacific~1Wallis.label@156d2c8f696d', 'Pacific/Wallis'],
    ['node.startAgentflow.root/inputs/scheduleTimezone/options/UTC.label@7e5f76c94a63', 'UTC'],
    ['node.startAgentflow.root/inputs/scheduleType.label@64e264ceff94', '调度类型'],
    ['node.startAgentflow.root/inputs/scheduleType/options/cronExpression.description@124fa4b1499f', '使用 Cron 表达式定义调度计划'],
    ['node.startAgentflow.root/inputs/scheduleType/options/cronExpression.label@26e53b6c1a78', 'Cron 表达式'],
    ['node.startAgentflow.root/inputs/scheduleType/options/visualPicker.description@ca6832fa7626', '使用可视化选择器设置调度选项'],
    ['node.startAgentflow.root/inputs/scheduleType/options/visualPicker.label@899a61261f7a', '可视化选择器'],
    ['node.startAgentflow.root/inputs/startEphemeralMemory.description@6e5d37ee3b44', '每次执行都从全新状态开始，不使用历史对话记录'],
    ['node.startAgentflow.root/inputs/startEphemeralMemory.label@ae2e02654d18', '临时记忆'],
    ['node.startAgentflow.root/inputs/startInputType.label@d04bdbc095f7', '输入类型'],
    ['node.startAgentflow.root/inputs/startInputType/options/chatInput.description@d0164189179e', '使用对话输入开始会话'],
    ['node.startAgentflow.root/inputs/startInputType/options/chatInput.label@a33cb48eae0a', '对话输入'],
    ['node.startAgentflow.root/inputs/startInputType/options/formInput.description@0a93ca084ed8', '使用表单输入启动工作流'],
    ['node.startAgentflow.root/inputs/startInputType/options/formInput.label@7fa34ae3166c', '表单输入'],
    [
        'node.startAgentflow.root/inputs/startInputType/options/scheduleInput.description@b0cc83b15e0e',
        '按照周期性调度计划（Cron）启动工作流'
    ],
    ['node.startAgentflow.root/inputs/startInputType/options/scheduleInput.label@d1fe4749e1d2', '定时输入'],
    ['node.startAgentflow.root/inputs/startInputType/options/webhookTrigger.description@fdee7d2501f5', '通过外部 Webhook 触发工作流'],
    ['node.startAgentflow.root/inputs/startInputType/options/webhookTrigger.label@30fd40067a0e', 'Webhook 触发'],
    ['node.startAgentflow.root/inputs/startPersistState.description@ea46e6ea84b6', '在同一会话中持久化状态'],
    ['node.startAgentflow.root/inputs/startPersistState.label@1a10b52bba18', '持久化状态'],
    ['node.startAgentflow.root/inputs/startState.description@5606007c1c6f', '工作流执行期间的运行时状态'],
    ['node.startAgentflow.root/inputs/startState.label@8ff821532c6c', '流程状态'],
    ['node.startAgentflow.root/inputs/startState/array/key.label@99a52df3ff3d', '键'],
    ['node.startAgentflow.root/inputs/startState/array/key.placeholder@1cbec737f863', '示例值一'],
    ['node.startAgentflow.root/inputs/startState/array/value.label@8e37953d23da', '值'],
    ['node.startAgentflow.root/inputs/startState/array/value.placeholder@95d64cacce0f', '示例值二'],
    [
        'node.startAgentflow.root/inputs/webhookBodyParams.description@480b0227d0f7',
        '定义 Webhook 请求体中的预期参数。留空表示接受任意 JSON 请求体。'
    ],
    ['node.startAgentflow.root/inputs/webhookBodyParams.label@290d0758209e', '预期请求体参数'],
    ['node.startAgentflow.root/inputs/webhookBodyParams/array/name.label@27c2ee034842', '变量名'],
    ['node.startAgentflow.root/inputs/webhookBodyParams/array/name.placeholder@3ec8afb54578', '例如 userId'],
    ['node.startAgentflow.root/inputs/webhookBodyParams/array/required.label@4850b174b713', '必填'],
    ['node.startAgentflow.root/inputs/webhookBodyParams/array/type.label@baaddf70fb5d', '类型'],
    ['node.startAgentflow.root/inputs/webhookBodyParams/array/type/options/array[boolean].label@166c9a7a0dde', '数组[布尔值]'],
    ['node.startAgentflow.root/inputs/webhookBodyParams/array/type/options/array[number].label@8a62b771d5aa', '数组[数字]'],
    ['node.startAgentflow.root/inputs/webhookBodyParams/array/type/options/array[object].label@2db24d614122', '数组[对象]'],
    ['node.startAgentflow.root/inputs/webhookBodyParams/array/type/options/array[string].label@b24c83413f09', '数组[字符串]'],
    ['node.startAgentflow.root/inputs/webhookBodyParams/array/type/options/boolean.label@a066ff921096', '布尔值'],
    ['node.startAgentflow.root/inputs/webhookBodyParams/array/type/options/number.label@bd82cf16699b', '数字'],
    ['node.startAgentflow.root/inputs/webhookBodyParams/array/type/options/object.label@62a6da8735c1', '对象'],
    ['node.startAgentflow.root/inputs/webhookBodyParams/array/type/options/string.label@b2ef230e7f4f', '字符串'],
    [
        'node.startAgentflow.root/inputs/webhookContentType.description@a3b0df1ea8ec',
        '传入请求应使用的 Content-Type。对于 application/x-www-form-urlencoded，如果完整负载是 "payload" 字段中的 JSON 字符串（例如 GitHub Webhook），系统会自动解析；之后可照常使用 $webhook.body.*。'
    ],
    ['node.startAgentflow.root/inputs/webhookContentType.label@59641229606e', '内容类型'],
    ['node.startAgentflow.root/inputs/webhookContentType/options/application~1json.label@bacb769b46f6', 'application/json'],
    [
        'node.startAgentflow.root/inputs/webhookContentType/options/application~1x-www-form-urlencoded.label@70f1a50a42c5',
        'application/x-www-form-urlencoded'
    ],
    [
        'node.startAgentflow.root/inputs/webhookDefaultInput.description@e231af8d6b37',
        '作为用户输入传递给下游节点的文本。使用 {{ $webhook.body.* }}、{{ $webhook.headers.* }} 或 {{ $webhook.query.* }} 插入传入请求中的字段。'
    ],
    ['node.startAgentflow.root/inputs/webhookDefaultInput.label@cfd55183e3d3', '自定义文本'],
    ['node.startAgentflow.root/inputs/webhookDefaultInput.placeholder@fc42d8d33340', '回答用户问题：{{ $webhook.body.question }}'],
    [
        'node.startAgentflow.root/inputs/webhookEnableAuth.description@5e876a83d9b8',
        '拒绝不含有效签名的传入请求。如果发送方（GitHub、Stripe、Slack、GitLab 等）使用共享密钥为每个请求签名，请启用此项，然后在下方生成密钥并复制到发送方。测试环境或可信网络中可保持关闭。'
    ],
    ['node.startAgentflow.root/inputs/webhookEnableAuth.label@262773ecf01d', '验证请求签名'],
    [
        'node.startAgentflow.root/inputs/webhookEnableValidation.description@4452f2f7be76',
        '拒绝缺少下方所声明必填请求头、请求体字段或查询参数的请求。启用此项可强制执行请求契约并提前拦截无效请求；关闭时接受任意负载，并由流程自行完成验证。'
    ],
    ['node.startAgentflow.root/inputs/webhookEnableValidation.label@8cbf46184366', '验证请求结构'],
    ['node.startAgentflow.root/inputs/webhookHeaderParams.description@ddfeabe78465', '声明预期的请求头。留空表示接受任意请求头。'],
    ['node.startAgentflow.root/inputs/webhookHeaderParams.label@a7fa1481a62a', '预期请求头'],
    ['node.startAgentflow.root/inputs/webhookHeaderParams/array/name.label@6e58dfc8e692', '请求头名称'],
    ['node.startAgentflow.root/inputs/webhookHeaderParams/array/name.placeholder@3828d39d88e0', '例如 x-github-event'],
    ['node.startAgentflow.root/inputs/webhookHeaderParams/array/required.label@4850b174b713', '必填'],
    ['node.startAgentflow.root/inputs/webhookInputMode.description@298507a391e8', 'Webhook 触发时，“开始”节点传递给后续流程的输入内容。'],
    ['node.startAgentflow.root/inputs/webhookInputMode.label@47ccf38c6f3e', '输入模式'],
    [
        'node.startAgentflow.root/inputs/webhookInputMode/options/none.description@3410041070f6',
        '不传入任何内容。请在下游节点配置中使用 $webhook.* 引用访问负载。'
    ],
    ['node.startAgentflow.root/inputs/webhookInputMode/options/none.label@3980333069ba', '无输入'],
    [
        'node.startAgentflow.root/inputs/webhookInputMode/options/payload.description@86ae5daf54b1',
        '传入经过 JSON 序列化的完整 Webhook 负载（请求体、请求头、查询参数）。适合调试，但会增大 LLM 上下文。'
    ],
    ['node.startAgentflow.root/inputs/webhookInputMode/options/payload.label@2fbd9c538558', '完整 Webhook 负载'],
    [
        'node.startAgentflow.root/inputs/webhookInputMode/options/text.description@8ec0d8a16d92',
        '传入固定字符串。可通过 $webhook.body.* / $webhook.headers.* / $webhook.query.* 引用 Webhook 字段。'
    ],
    ['node.startAgentflow.root/inputs/webhookInputMode/options/text.label@cfd55183e3d3', '自定义文本'],
    ['node.startAgentflow.root/inputs/webhookMethod.label@596fe2e088b3', 'HTTP 方法'],
    ['node.startAgentflow.root/inputs/webhookMethod/options/DELETE.label@65daeb378bde', 'DELETE'],
    ['node.startAgentflow.root/inputs/webhookMethod/options/GET.label@14e30cd163c7', 'GET'],
    ['node.startAgentflow.root/inputs/webhookMethod/options/PATCH.label@8dce33b49f31', 'PATCH'],
    ['node.startAgentflow.root/inputs/webhookMethod/options/POST.label@9aee6b1bcdf6', 'POST'],
    ['node.startAgentflow.root/inputs/webhookMethod/options/PUT.label@907bf9a40f9c', 'PUT'],
    ['node.startAgentflow.root/inputs/webhookQueryParams.description@60677d5106c6', '声明预期的查询参数。留空表示接受任意参数。'],
    ['node.startAgentflow.root/inputs/webhookQueryParams.label@e97e165a260a', '预期查询参数'],
    ['node.startAgentflow.root/inputs/webhookQueryParams/array/name.label@27c2ee034842', '变量名'],
    ['node.startAgentflow.root/inputs/webhookQueryParams/array/name.placeholder@ccd00102ff24', '例如 page'],
    ['node.startAgentflow.root/inputs/webhookQueryParams/array/required.label@4850b174b713', '必填'],
    ['node.startAgentflow.root/inputs/webhookResponseMode.description@5f0c466aef1d', 'Flowise 响应传入 Webhook 请求的方式。'],
    ['node.startAgentflow.root/inputs/webhookResponseMode.label@fd67a10a74e5', '响应模式'],
    [
        'node.startAgentflow.root/inputs/webhookResponseMode/options/async.description@7d16d45ce3a7',
        '立即返回 202 Accepted，并在后台运行流程。可在下方设置回调 URL，以便流程完成后通过 POST 发送结果；留空则采用“触发后不等待”模式。适合 HTTP 超时时间较短的发送方。'
    ],
    ['node.startAgentflow.root/inputs/webhookResponseMode/options/async.label@e84cc7931ac2', '异步（回调）'],
    [
        'node.startAgentflow.root/inputs/webhookResponseMode/options/stream.description@e5191d9c6d11',
        '返回 Server-Sent Events 流，让调用方实时查看 Token 和智能体步骤。适合自定义调用方（使用 fetch+ReadableStream 的浏览器、内部服务），不兼容期望快速获得单次响应的发送方。'
    ],
    ['node.startAgentflow.root/inputs/webhookResponseMode/options/stream.label@5d21934a76f7', '流式响应（SSE）'],
    [
        'node.startAgentflow.root/inputs/webhookResponseMode/options/sync.description@19a2691d6f05',
        '等待流程完成并以 JSON 返回完整结果。方式简单，但会阻塞调用方；对于 HTTP 等待窗口较短的发送方可能超时。'
    ],
    ['node.startAgentflow.root/inputs/webhookResponseMode/options/sync.label@b31baf7cfc29', '同步'],
    [
        'node.startAgentflow.root/inputs/webhookSecret.description@2cfa30d47818',
        '点击“生成密钥”创建随机共享密钥，然后将其复制到发送方，以便为每个请求签名。请使用下方的“签名请求头”和“签名类型”匹配发送方传递签名的方式。'
    ],
    ['node.startAgentflow.root/inputs/webhookSecret.label@af8d09189efa', 'Webhook 密钥'],
    [
        'node.startAgentflow.root/inputs/webhookSignatureHeader.description@929d11998b2c',
        '用于携带签名的请求头。例如：GitHub 使用 x-hub-signature-256，Stripe 使用 stripe-signature，GitLab 使用 x-gitlab-token。'
    ],
    ['node.startAgentflow.root/inputs/webhookSignatureHeader.label@56806a27fc0d', '签名请求头'],
    ['node.startAgentflow.root/inputs/webhookSignatureHeader.placeholder@14c30578d0e4', 'x-webhook-signature'],
    [
        'node.startAgentflow.root/inputs/webhookSignatureType.description@92555414b769',
        '签名验证方式。GitHub、Stripe、Slack 使用 HMAC-SHA256（自动支持 sha256=<hex> 前缀）；GitLab 风格的明文密钥比较使用纯 Token。'
    ],
    ['node.startAgentflow.root/inputs/webhookSignatureType.label@112725a435ef', '签名类型'],
    ['node.startAgentflow.root/inputs/webhookSignatureType/options/hmac-sha256.label@f9a4ecea0836', 'HMAC-SHA256'],
    ['node.startAgentflow.root/inputs/webhookSignatureType/options/plain-token.label@1e3e696cacd6', '纯 Token'],
    ['node.startAgentflow.root/inputs/webhookURL.description@6cb9e39872dd', '向此 URL 发送请求以触发工作流'],
    ['node.startAgentflow.root/inputs/webhookURL.label@84805a7574a8', 'Webhook URL']
]
