export const ZH_CN_AGENTFLOW_C: ReadonlyArray<readonly [string, string]> = [
    ['node.executeFlowAgentflow.root.description@30e6353e383e', '执行另一个流程'],
    ['node.executeFlowAgentflow.root.label@aa5516bf4d96', '执行流程'],
    ['node.executeFlowAgentflow.root/credential.label@4fd0f54ac1c9', '连接凭据'],
    [
        'node.executeFlowAgentflow.root/inputs/executeFlowBaseURL.description@84e20cfffbee',
        'Flowise 的基础 URL。默认使用传入请求的 URL；需要通过备用路由执行流程时可设置此项。'
    ],
    ['node.executeFlowAgentflow.root/inputs/executeFlowBaseURL.label@70589413a3c9', '基础 URL'],
    ['node.executeFlowAgentflow.root/inputs/executeFlowBaseURL.placeholder@f1de9e489ba8', 'http://localhost:3000'],
    ['node.executeFlowAgentflow.root/inputs/executeFlowInput.label@36ecb4f86691', '输入'],
    ['node.executeFlowAgentflow.root/inputs/executeFlowOverrideConfig.description@a2b5b2551fef', '覆盖传递给流程的配置'],
    ['node.executeFlowAgentflow.root/inputs/executeFlowOverrideConfig.label@11e524377a1e', '覆盖配置'],
    ['node.executeFlowAgentflow.root/inputs/executeFlowReturnResponseAs.label@ba98ff33219c', '响应返回格式'],
    ['node.executeFlowAgentflow.root/inputs/executeFlowReturnResponseAs/options/assistantMessage.label@a23e1001767c', '助手消息'],
    ['node.executeFlowAgentflow.root/inputs/executeFlowReturnResponseAs/options/userMessage.label@fb33af32d694', '用户消息'],
    ['node.executeFlowAgentflow.root/inputs/executeFlowSelectedFlow.label@4005e542b078', '选择流程'],
    ['node.executeFlowAgentflow.root/inputs/executeFlowUpdateState.description@e1092381d050', '在工作流执行期间更新运行时状态'],
    ['node.executeFlowAgentflow.root/inputs/executeFlowUpdateState.label@12cccc3a460b', '更新流程状态'],
    ['node.executeFlowAgentflow.root/inputs/executeFlowUpdateState/array/key.label@99a52df3ff3d', '键'],
    ['node.executeFlowAgentflow.root/inputs/executeFlowUpdateState/array/value.label@8e37953d23da', '值'],
    ['node.httpAgentflow.root.description@3fb1c3577970', '发送 HTTP 请求'],
    ['node.httpAgentflow.root.label@56d6f32151ad', 'HTTP'],
    ['node.httpAgentflow.root/credential.label@f11b625da716', 'HTTP 凭据'],
    ['node.httpAgentflow.root/inputs/body.label@6ccaa6415b5e', '请求体'],
    ['node.httpAgentflow.root/inputs/body.label@6ccaa6415b5e', '请求体'],
    ['node.httpAgentflow.root/inputs/body/array/key.label@99a52df3ff3d', '键'],
    ['node.httpAgentflow.root/inputs/body/array/value.label@8e37953d23da', '值'],
    ['node.httpAgentflow.root/inputs/bodyType.label@d4f909e62a8f', '请求体类型'],
    ['node.httpAgentflow.root/inputs/bodyType/options/formData.label@bf52c5f5e6ba', '表单数据'],
    ['node.httpAgentflow.root/inputs/bodyType/options/json.label@db1a21a0bc2e', 'JSON'],
    ['node.httpAgentflow.root/inputs/bodyType/options/raw.label@848123d14f84', '原始内容'],
    ['node.httpAgentflow.root/inputs/bodyType/options/xWwwFormUrlencoded.label@9ebba27dd385', 'x-www-form-urlencoded'],
    ['node.httpAgentflow.root/inputs/headers.label@194e9fe656a1', '请求头'],
    ['node.httpAgentflow.root/inputs/headers/array/key.label@99a52df3ff3d', '键'],
    ['node.httpAgentflow.root/inputs/headers/array/value.label@8e37953d23da', '值'],
    ['node.httpAgentflow.root/inputs/method.label@52a0f9b65b27', '请求方法'],
    ['node.httpAgentflow.root/inputs/method/options/DELETE.label@65daeb378bde', 'DELETE'],
    ['node.httpAgentflow.root/inputs/method/options/GET.label@14e30cd163c7', 'GET'],
    ['node.httpAgentflow.root/inputs/method/options/PATCH.label@8dce33b49f31', 'PATCH'],
    ['node.httpAgentflow.root/inputs/method/options/POST.label@9aee6b1bcdf6', 'POST'],
    ['node.httpAgentflow.root/inputs/method/options/PUT.label@907bf9a40f9c', 'PUT'],
    ['node.httpAgentflow.root/inputs/queryParams.label@4f3d55a6de82', '查询参数'],
    ['node.httpAgentflow.root/inputs/queryParams/array/key.label@99a52df3ff3d', '键'],
    ['node.httpAgentflow.root/inputs/queryParams/array/value.label@8e37953d23da', '值'],
    ['node.httpAgentflow.root/inputs/responseType.label@3b2ffe2c5bf3', '响应类型'],
    ['node.httpAgentflow.root/inputs/responseType/options/arraybuffer.label@037d43cb687c', '数组缓冲区'],
    ['node.httpAgentflow.root/inputs/responseType/options/base64.label@85f85fe43e27', '原始内容（Base64）'],
    ['node.httpAgentflow.root/inputs/responseType/options/json.label@db1a21a0bc2e', 'JSON'],
    ['node.httpAgentflow.root/inputs/responseType/options/text.label@71988c4d8e08', '文本'],
    ['node.httpAgentflow.root/inputs/url.label@e7a241debad5', 'URL'],
    ['node.humanInputAgentflow.root.description@2b845143caa7', '在执行期间请求人工输入、批准或拒绝'],
    ['node.humanInputAgentflow.root.label@d7c8a913b456', '人工输入'],
    ['node.humanInputAgentflow.root/outputs/proceed.label@f01847dfc941', '继续'],
    ['node.humanInputAgentflow.root/outputs/reject.label@ab604a360777', '拒绝'],
    ['node.humanInputAgentflow.root/inputs/humanInputDescription.label@526e0087cc3f', '说明'],
    ['node.humanInputAgentflow.root/inputs/humanInputDescription.placeholder@a87f8b9622bf', '确定要继续吗？'],
    ['node.humanInputAgentflow.root/inputs/humanInputDescriptionType.label@8d3b87d1c3cb', '说明类型'],
    ['node.humanInputAgentflow.root/inputs/humanInputDescriptionType/options/dynamic.description@0eea76d10e89', '使用 LLM 生成说明'],
    ['node.humanInputAgentflow.root/inputs/humanInputDescriptionType/options/dynamic.label@b6ee7b3e8d9c', '动态'],
    ['node.humanInputAgentflow.root/inputs/humanInputDescriptionType/options/fixed.description@abf6003f2404', '指定固定说明'],
    ['node.humanInputAgentflow.root/inputs/humanInputDescriptionType/options/fixed.label@1246fc93bca0', '固定'],
    ['node.humanInputAgentflow.root/inputs/humanInputEnableFeedback.label@323305d402c2', '启用反馈'],
    ['node.humanInputAgentflow.root/inputs/humanInputModel.label@5e2c614c23f0', '模型'],
    ['node.humanInputAgentflow.root/inputs/humanInputModelPrompt.label@5c39123805ff', '提示词'],
    ['node.iterationAgentflow.root.description@8ba6d51f0250', '对迭代块中的节点执行 N 次迭代'],
    ['node.iterationAgentflow.root.label@baf6d316dc75', '迭代'],
    ['node.iterationAgentflow.root/inputs/iterationInput.description@61221368a3a0', '要逐项迭代的输入数组'],
    ['node.iterationAgentflow.root/inputs/iterationInput.label@d8e5142f17b0', '数组输入'],
    ['node.loopAgentflow.root.description@19b88a5ce568', '循环回到之前的节点'],
    ['node.loopAgentflow.root.hint@df2116267ebf', '请确保已在大模型／智能体节点中启用记忆，以保留对话历史'],
    ['node.loopAgentflow.root.label@f2f6a0188995', '循环'],
    ['node.loopAgentflow.root/inputs/fallbackMessage.description@821158b19ba6', '超过循环次数限制时显示的消息'],
    ['node.loopAgentflow.root/inputs/fallbackMessage.label@d6bf62d64fac', '备用消息'],
    ['node.loopAgentflow.root/inputs/fallbackMessage.placeholder@2416a345b057', '请在此输入备用消息'],
    ['node.loopAgentflow.root/inputs/loopBackToNode.label@1b4a11abe399', '循环返回至'],
    ['node.loopAgentflow.root/inputs/loopUpdateState.description@e1092381d050', '在工作流执行期间更新运行时状态'],
    ['node.loopAgentflow.root/inputs/loopUpdateState.label@12cccc3a460b', '更新流程状态'],
    ['node.loopAgentflow.root/inputs/loopUpdateState/array/key.label@99a52df3ff3d', '键'],
    ['node.loopAgentflow.root/inputs/loopUpdateState/array/value.label@8e37953d23da', '值'],
    ['node.loopAgentflow.root/inputs/maxLoopCount.label@cb058c20f4bc', '最大循环次数']
]
